apiVersion: apps/v1
kind: Deployment
metadata:
  name: po-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: po-frontend
  template:
    metadata:
      labels:
        app: po-frontend
    spec:
      containers:
      - name: frontend
        image: your-docker-username/po-generator-frontend:IMAGE_TAG
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: po-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
